const test = require('ava')

test.todo('farmer.start')
test.todo('farmer.stop')
test.todo('farmer.generateQuote')
test.todo('farmer.validateAgreement')
test.todo('farmer.signAgreement')
test.todo('farmer.validateSow')
test.todo('farmer.dataTransmitted')
test.todo('farmer.validateReward')
test.todo('farmer.generateReceipt')
test.todo('farmer.onHireConfirmed')
