const test = require('ava')

test.todo('farmer.startBroadcast')
test.todo('farmer.stopBroadcast')
test.todo('farmer.generateQuote')
test.todo('farmer.validateAgreement')
test.todo('farmer.signAgreement')
test.todo('farmer.validateSow')
test.todo('farmer.dataTransmitted')
test.todo('farmer.startBroadcast')
test.todo('farmer.validateReward')
test.todo('farmer.generateReceipt')
test.todo('farmer.startWork')
