const test = require('ava')

test.todo('requester.appendToAutoQueue')
test.todo('requester.startBroadcast')
test.todo('requester.stopBroadcast')
test.todo('requester.setupContentSwarm')
test.todo('requester.submitJob')
test.todo('requester.validateQuote')
test.todo('requester.generateAgreement')
test.todo('requester.validateAgreement')
test.todo('requester.onHireConfirmed')
test.todo('requester.onReceipt')
test.todo('requester.dataReceived')
test.todo('requester.sendRewards')
test.todo('requester.generateReward')
test.todo('requester.startWork')
