const test = require('ava')

test.todo('requester.start')
test.todo('requester.stop')
test.todo('requester.prepareJob')
test.todo('requester.validateQuote')
test.todo('requester.generateAgreement')
test.todo('requester.validateAgreement')
test.todo('requester.onHireConfirmed')
test.todo('requester.onReceipt')
test.todo('requester.dataReceived')
test.todo('requester.sendRewards')
test.todo('requester.generateReward')