const DEFAULT_REWARD_PERCENTAGE = 0.1
const DEFAULT_CONFIG_STORE = 'store.json'
const DEFAULT_JOB_STORE = 'jobs.json'
const DEFAULT_MAX_PEERS = 10
const DEFAULT_TIMEOUT = 6000

module.exports = {
  DEFAULT_REWARD_PERCENTAGE,
  DEFAULT_CONFIG_STORE,
  DEFAULT_JOB_STORE,
  DEFAULT_MAX_PEERS,
  DEFAULT_TIMEOUT
}
